### ISSUE TITLE
Implement doc-deploy-index actions

### ISSUE THREAD

**Issue by jorgepiloto** [ansys/actions#294]
💡 **Idea**
With [pymeilisearch](https://github.com/ansys/pymeilisearch) public, it is possible now for projects to upload indexed documentation.

Two actions should be implemented: `doc-deploy-dev-index` and `doc-deploy-stable-index`. These actions should be used in the following manner:

```yml
- name: "Doc deploy dev index"
  uses: ansys/actions/doc-deploy-dev-index@v4
    with:
      - doc-artifact-name: ...
      - cname: ...
      - library-name: ...             # Extract version number from here
      - host-url: ...
      - api-key: ...
```
