### ISSUE TITLE
doc-build@v6: pyproject.toml repositories need use-python-cache: false

### ISSUE THREAD

**Issue by anscfrisson** [ansys/actions#461]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

With doc-build@v6 repositories containing `pyproject.toml` need to add `use-python-cache: false` as workaround, otherwise the action fails:
```error
Run ansys/actions/doc-build@v6
Run ansys/actions/_setup-python@v6
Run actions/setup-python@v5
Installed versions
  Successfully set up CPython (3.10.14)
Error: No file in /home/runner/work/*** matched to [pyproject.toml or **/pyproject.toml], make sure you have checked out the target repository
```
(`***`: internal repository)

Note: this is probably due to:

- setting up python before checking out the repository in https://github.com/ansys/actions/blob/v6/doc-build/action.yml
  ```yaml
      - name: "Set up Python"
        uses: ansys/actions/_setup-python@v6
        with:
          python-version: ${{ inputs.python-version }}
          use-cache: ${{ inputs.use-python-cache }}
      - name: "Install Git and clone project"
        uses: actions/checkout@v4
        if: ${{ inputs.checkout == 'true' }}
  ```
-  `cache-dependency-path: 'pyproject.toml` in: 
https://github.com/ansys/actions/blob/main/_setup-python/action.yml
  ```yaml
      - name: "Set up Python using cache"
        uses: actions/setup-python@v5
        if: inputs.use-cache == 'true'
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'
          cache-dependency-path: 'pyproject.toml'
      - name: "Set up Python without using cache"
        uses: actions/setup-python@v5
        if: inputs.use-cache == 'false'
        with:
          python-version: ${{ inputs.python-version }}
  ```

### 📝 Steps to reproduce

Configure `ansys/actions/doc-build@v6` as follows:
```yaml
      - uses: ansys/actions/doc-build@v6
        with:
          python-version: ${{ env.MAIN_PYTHON_VERSION }}
          use-python-cache: true
```
(or without `use-python-cache: true` as `use-python-cache` defaults to `false`)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

242

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
accessible-pygments==0.0.4
alabaster==0.7.16
annotated-types==0.6.0
*** (internal repository)
ansys-sphinx-theme==0.15.2
autoflake==2.3.1
Babel==2.14.0
backports.tarfile==1.0.0
beautifulsoup4==4.12.3
build==1.2.1
CacheControl==0.14.0
cachetools==5.3.3
certifi==2024.2.2
chardet==5.2.0
charset-normalizer==3.3.2
cleo==2.1.0
click==8.1.7
click-option-group==0.5.6
colorama==0.4.6
coverage==7.4.4
crashtest==0.4.1
distlib==0.3.8
docutils==0.20.1
dotty-dict==1.3.1
dulwich==0.21.7
exceptiongroup==1.2.0
fastjsonschema==2.19.1
filelock==3.13.4
gitdb==4.0.11
GitPython==3.1.43
idna==3.7
imagesize==1.4.1
importlib_metadata==7.1.0
importlib_resources==6.4.0
iniconfig==2.0.0
installer==0.7.0
jaraco.classes==3.4.0
jaraco.context==5.3.0
jaraco.functools==4.0.0
Jinja2==3.1.3
keyring==25.1.0
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
more-itertools==10.2.0
msgpack==1.0.8
nh3==0.2.17
numpydoc==1.7.0
packaging==24.0
pexpect==4.9.0
pkginfo==1.10.0
platformdirs==4.2.0
pluggy==1.4.0
poetry==1.8.2
poetry-core==1.9.0
poetry-plugin-export==1.7.1
ptyprocess==0.7.0
pydantic==2.7.0
pydantic_core==2.18.1
pydata-sphinx-theme==0.14.4
pyflakes==3.2.0
Pygments==2.17.2
pyproject-api==1.6.1
pyproject_hooks==1.0.0
pytest==8.1.1
pytest-cov==5.0.0
python-gitlab==4.4.0
python-semantic-release==9.4.2
pytz==2024.1
pywin32-ctypes==0.2.2
rapidfuzz==3.8.1
readme_renderer==43.0
requests==2.31.0
requests-toolbelt==1.0.0
rfc3986==2.0.0
rich==13.7.1
shellingham==1.5.4
smmap==5.0.1
snowballstemmer==2.2.0
soupsieve==2.5
Sphinx==7.2.6
sphinx-copybutton==0.5.2
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
tabulate==0.9.0
tomli==2.0.1
tomlkit==0.12.4
tox==4.14.2
trove-classifiers==2024.4.10
twine==5.0.0
typing_extensions==4.11.0
tzdata==2024.1
urllib3==2.2.1
virtualenv==20.25.1
zipp==3.18.1
```
