### ISSUE TITLE
`smoke-test-module` input

### ISSUE THREAD

**Issue by germa89** [ansys/actions#859]
I do not think it is a good idea to have a fixed way to test the module.

https://github.com/ansys/actions/blob/da9e73e851cffbff51f850c19c639fb9738e22fa/build-wheelhouse/action.yml#L410

Why not?

```yml
  smoke-test-module:
    description: |
      Code to execute to test the python import.
    default: ''
    required: false
    type: string

...

    - name: Run smoke test
      if: inputs.smoke-test-module != ''
      env:
        ACTIVATE_VENV: ${{ steps.virtual-environment-activation-command.outputs.ACTIVATE_VENV }}
      shell: bash
      run: |
        ${ACTIVATE_VENV}
        python -c "${{ inputs.smoke-test-module }}"
```

Futhermore, I would probably make the testing mandatory by:

```yml
  smoke-test-module:
    description: |
      Code to execute to test the python import.
    default: "import ${MODULE}; from ${MODULE} import __version__; print(f'Imported: {${MODULE}}, version: {__version__}')"
    required: false
    type: string

...

    - name: Run smoke test
      if: inputs.smoke-test-module != ''
      env:
        MODULE: ${{ inputs.smoke-test-module }}
        ACTIVATE_VENV: ${{ steps.virtual-environment-activation-command.outputs.ACTIVATE_VENV }}
      shell: bash
      run: |
        ${ACTIVATE_VENV}
        python -c "${{ inputs.smoke-test-module }}" # check for right combination of single and double ticks
```

You still dan disable it by leaving it empty... but by default it will try to run your code unless specific string is provided.

**Comment by SMoraisAnsys** [comment]
@germa89 I'm not sure to understand your point on the issue description. Is it that you want the smoke tests to be mandatory ?

I like your idea of an output though ! This would make things more closer to the previous implementation.

**Comment by SMoraisAnsys** [comment]
> Allowing users to have an input that directly executes presents a big vulnerability.
> 
> Either we keep the original command or completely remove the import. Honestly, the wheelhouse should just build this artifact and not be confused with smoke tests, which are short and quick tests.

I do agree with limiting the action to building wheelhouse and sbom. The extra input has been added to allow keeping previous behavior available.

**Comment by RobPasMue** [comment]
> adding a new input to execute a script provided by users (e.g. .ci/whatever.sh) to allow a larger usage of our actions

That is still a vulnerability @SMoraisAnsys -- and I believe we did not get to implement it, right? With the latest security concerns, I have the feeling it's a no-go

**Comment by germa89** [comment]
> If users have writz access then they already can run arbitrary code. If thzy dont then mainteners have to check changes before allowing them to be run in CICD

This. If I want, I can do this:

```
- name: "Build wheelhouse and perform smoke test"
  id: build-wheelhouse
  uses: ansys/actions/build-wheelhouse@main
  with:
    library-name: ${{ env.PACKAGE_NAME }}
    operating-system: ${{ matrix.os }}
    python-version: ${{ matrix.python-version }}
    check-licenses: true

- name: "Listing the files... and inject whatever
  run: |
      ls -R # to see the files
      ./inject_malicious_code.sh
      ./leak_secrets.sh
```

And while I agree, that the input will allow the execution of arbitrary code, I guess that is a concern when the environment you are running in is IP-protected or sensitive in some way. But I don't think the environment created by the action has any sensitive information. If there was, you should not go for a composite action that allows previous/post steps. We should go for reusable workflows so the user is not allow/cannot modify it.

I do understand we are under a lot of pressure to improve the security across our repos, but I think the concern in this case is not applicable.
